# Generated by Django 5.2.5 on 2025-08-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_pin_reset_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='two_fa_enabled',
            new_name='two_factor_enabled',
        ),
    ]
