# Generated by Django 5.2.5 on 2025-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
