# Generated by Django 5.2.5 on 2025-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawalrequest_denial_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
