# Generated by Django 5.2.5 on 2025-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'KYC Submission', 'verbose_name_plural': 'KYC Submissions'},
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='document_file',
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/documents/back/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='document_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/documents/front/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('national_id', 'National ID')], max_length=50, null=True),
        ),
    ]
